name: Index Report

on:
  schedule:
    # ğŸ‡°ğŸ‡· ì˜¤ì „ 7ì‹œ (UTC 22:00 ì „ë‚ )
    - cron: "0 22 * * 1-5"

    # ğŸ‡°ğŸ‡· ì˜¤í›„ 4ì‹œ (UTC 07:00)
    - cron: "0 7 * * 1-5"

  workflow_dispatch:  # ìˆ˜ë™ ì‹¤í–‰ ë²„íŠ¼

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install yfinance requests

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas openpyxl requests beautifulsoup4 python-telegram-bot matplotlib


      - name: Run Index bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python Index.py
